annotations:
  catalog.cattle.io/display-name: SUSE Observability Agent
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/release-name: suse-observability
apiVersion: v2
appVersion: 3.0.0
dependencies:
- alias: httpHeaderInjectorWebhook
  condition: httpHeaderInjectorWebhook.enabled
  name: http-header-injector
  repository: file://./charts/http-header-injector
  version: 0.0.21
- condition: kubernetes-rbac-agent.enabled
  name: kubernetes-rbac-agent
  repository: file://./charts/kubernetes-rbac-agent
  version: 0.0.20
description: Helm chart for the SUSE observability Agent.
home: https://github.com/StackVista/stackstate-agent
icon: file://assets/logos/suse-observability-agent.svg
keywords:
- monitoring
- observability
- SUSE
maintainers:
- email: suse-observability-ops@suse.com
  name: SUSE
name: suse-observability-agent
version: 108.0.0+up1.2.16
