url: local
version: 108.0.0+up0.1.5
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
