apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "rancher-supportability-review.fullname" . }}-rb
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "rancher-supportability-review.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "rancher-supportability-review.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
