auto: true
url: https://github.com/rancher/fleet.git
chartRepoBranch: add_correct_versions_to_charts_v0.11
subdirectory: charts/fleet
additionalCharts:
  - workingDir: fleet-crd
    upstreamOptions:
      url: https://github.com/rancher/fleet.git
      chartRepoBranch: add_correct_versions_to_charts_v0.11
      subdirectory: charts/fleet-crd
  - workingDir: fleet-agent
    upstreamOptions:
      url: https://github.com/rancher/fleet.git
      chartRepoBranch: add_correct_versions_to_charts_v0.11
      subdirectory: charts/fleet-agent
