auto: true
url: https://github.com/rancher/fleet.git
chartRepoBranch: release/v0.11
subdirectory: charts/fleet
additionalCharts:
  - workingDir: fleet-agent
    upstreamOptions:
      url: https://github.com/rancher/fleet.git
      chartRepoBranch: release/v0.11
      subdirectory: charts/fleet-agent
  - workingDir: fleet-crd
    upstreamOptions:
      url: https://github.com/rancher/fleet.git
      chartRepoBranch: release/v0.11
      subdirectory: charts/fleet-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true