apiVersion: v1
kind: ConfigMap
metadata:
  name: llm-config
  namespace: cattle-ai-agent-system
data:
  OLLAMA_MODEL: "{{ .Values.ollamaLlmModel }}"
  GEMINI_MODEL: "{{ .Values.geminiLlmModel }}"
  OPENAI_MODEL: "{{ .Values.openaiLlmModel }}"
  BEDROCK_MODEL: "{{ .Values.bedrockLlmModel }}"
  ACTIVE_LLM: "{{ .Values.activeLlm }}"
