workingDir: ""
url: https://github.com/rancher/ob-team-charts.git
subdirectory: charts/rancher-monitoring/77.9.1-rancher.23/charts/grafana
commit: 995f043849d2af123acae016c0c37fee449e9d5f
ignoreDependencies: []
replacePaths: []
