workingDir: ""
url: https://github.com/rancher/ob-team-charts.git
subdirectory: charts/rancher-monitoring/80.9.1-rancher.3/charts/grafana
commit: 47e87cfd02fddbd500585497a886f60fdebe9d4c
ignoreDependencies: []
replacePaths: []
