url: https://github.com/rancher/ob-team-charts.git
subdirectory: charts/rancher-monitoring/69.8.2-rancher.34
commit: 800b5b5072bfeb6a79964ecc5bd7f89ec8b9cd81
version: 106.1.7-rc.2
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/ob-team-charts.git
      subdirectory: charts/rancher-monitoring-crd/69.8.2-rancher.34
      commit: 800b5b5072bfeb6a79964ecc5bd7f89ec8b9cd81
doNotRelease: false
