{
 "title": "Kubernetes Components",
 "description": "-",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "API Server Request Rates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (rate(apiserver_request_count{code!~\"2..\"}[5m]))",
     "legendFormat": "Error Rate"
    },
    {
     "expr": "sum by(instance) (rate(apiserver_request_count[5m]))",
     "legendFormat": "Request Rate"
    }
   ]
  },
  {
   "title": "API Server Request Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(verb) (rate(apiserver_latency_seconds:quantile[5m]) >= 0)"
    }
   ]
  },
  {
   "title": "Nginx Ingress Request Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(nginx_requests_total[1m])", "legendFormat": "Request Rate" }
   ]
  },
  {
   "title": "Controller Manager Queue Depth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "service_depth", "legendFormat": "Service Depth" },
    { "expr": "volumes_depth", "legendFormat": "Volumes Depth" },
    { "expr": "replicationmanager_depth", "legendFormat": "Replication Manager Depth" },
    { "expr": "statefulset_depth", "legendFormat": "StatefulSet Depth" },
    { "expr": "serviceaccount_depth", "legendFormat": "Service Account Depth" },
    { "expr": "endpoint_depth", "legendFormat": "Endpoint Depth" },
    { "expr": "deployment_depth", "legendFormat": "Deployment Depth" },
    { "expr": "daemonset_depth", "legendFormat": "DaemonSet Depth" }
   ]
  }
 ]
}