{
 "title": "Rancher Components",
 "description": "A quick dashboard for displaying Fluentd metrics.",
 "time": { "from": "2017-10-20T13:00:11.189Z", "to": "2017-10-20T13:38:24.045Z" },
 "panels": [
  {
   "title": "Fluentd buffer queue length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "fluentd_buffer_queue_length" }
   ]
  },
  {
   "title": "Fluentd buffer total queued size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fluentd_buffer_total_queued_size"
    }
   ]
  },
  {
   "title": "Fluentd Up",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "fluentd_up" }
   ]
  },
  {
   "title": "Fluentd retry count (apache)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fluentd_retry_count{pluginCategory=\"output\",pluginId=\"apache_log\"}"
    }
   ]
  }
 ]
}