workingDir: ""
url: https://github.com/rancher/ob-team-charts.git
subdirectory: charts/rancher-monitoring/77.9.1-rancher.26/charts/prometheus-adapter
commit: b375d5d93e4491bc00c2c16d3cafa04f53a531e5
ignoreDependencies: []
replacePaths: []
