workingDir: ""
url: https://github.com/rancher/ob-team-charts.git
subdirectory: charts/rancher-monitoring/69.8.2-rancher.36/charts/prometheus-adapter
commit: 4a173c3d8d732aa12e760a5a318fb9b86e3ce547
ignoreDependencies: []
replacePaths: []
