apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "rancher-supportability-review.fullname" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "delete"]
