apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: '{{ .Release.Name }}'
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods/log
  - pods/status
  - services/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - elemental.cattle.io
  resources:
  - machineinventories
  - machineinventoryselectors
  - machineregistrations
  - managedosimages
  - managedosversionchannels
  - managedosversions
  - seedimages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elemental.cattle.io
  resources:
  - machineinventories/status
  - machineregistrations/status
  - seedimages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elemental.cattle.io
  resources:
  - machineinventoryselectors/status
  - managedosimages/status
  - managedosversionchannels/status
  - managedosversions/status
  verbs:
  - get
  - list
  - patch
  - update
- apiGroups:
  - fleet.cattle.io
  resources:
  - bundles
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - settings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - list
  - watch
