url: https://github.com/rancher/backup-restore-operator/releases/download/v10.0.0-rc.1/rancher-backup-10.0.0-rc.1.tgz
version: 109.0.0
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/backup-restore-operator/releases/download/v10.0.0-rc.1/rancher-backup-crd-10.0.0-rc.1.tgz
