url: https://github.com/rancher/backup-restore-operator/releases/download/v8.1.0/rancher-backup-8.1.0.tgz
version: 107.1.0
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/backup-restore-operator/releases/download/v8.1.0/rancher-backup-crd-8.1.0.tgz
