global:
  cattle:
    systemDefaultRegistry: ""

systemUpgradeController:
  image:
    repository: rancher/system-upgrade-controller
    tag: v0.19.1

kubectl:
  image:
    repository: rancher/kuberlr-kubectl
    tag: v7.0.1 # For compatibility and versioning, see https://github.com/rancher/kuberlr-kubectl
