image:
  empty: rancher/pause:3.1
  repository: "rancher/mirrored-elemental-operator"
  tag: "1.8.1"
  imagePullPolicy: IfNotPresent

seedImage:
  repository: "rancher/mirrored-elemental-seedimage-builder"
  tag: "1.8.1"
  imagePullPolicy: IfNotPresent

# a custom channel to install
#channel:
#  name: "my-os-channel"
#  image: "my-repo/my-os-channel"
#  tag: "1.2.3"

# default Elemental channels
defaultChannels:
  slMicro62Baremetal:
    included: true
    name: sl-micro-6.2-baremetal-channel
    enabled: true
    image: "registry.suse.com/rancher/elemental-channel/sl-micro:6.2-baremetal"
    deleteNoLongerInSyncVersions: true
  slMicro62Base:
    included: true
    name: sl-micro-6.2-base-channel
    enabled: false
    image: "registry.suse.com/rancher/elemental-channel/sl-micro:6.2-base"
    deleteNoLongerInSyncVersions: true
  slMicro62KVM:
    included: true
    name: sl-micro-6.2-kvm-channel
    enabled: false
    image: "registry.suse.com/rancher/elemental-channel/sl-micro:6.2-kvm"
    deleteNoLongerInSyncVersions: true
  slMicro62RT:
    included: true
    name: sl-micro-6.2-rt-channel
    enabled: false
    image: "registry.suse.com/rancher/elemental-channel/sl-micro:6.2-rt"
    deleteNoLongerInSyncVersions: true

# number of operator replicas to deploy
replicas: 1

# http[s] proxy server
# proxy: http://<username>@<password>:<url>:<port>

# comma separated list of domains or ip addresses that will not use the proxy
noProxy: 127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local

global:
  cattle:
    systemDefaultRegistry: ""

# used only if systemDefaultRegistry is empty
registryUrl: ""

# enable debug output for operator
debug: false

nodeSelector:
  kubernetes.io/os: linux

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 2000

tolerations:
  - key: cattle.io/os
    operator: "Equal"
    value: "linux"
    effect: NoSchedule
