url: https://github.com/rancher/ob-team-charts.git
subdirectory: charts/rancher-monitoring/69.8.2-rancher.30
commit: dff04e9e78746c5dfb8db7b7d2e2f02846b9647d
version: 107.2.4-rc.1
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/ob-team-charts.git
      subdirectory: charts/rancher-monitoring-crd/69.8.2-rancher.30
      commit: dff04e9e78746c5dfb8db7b7d2e2f02846b9647d
doNotRelease: false
