url: https://github.com/rancher/ob-team-charts.git
subdirectory: charts/rancher-monitoring/80.9.1-rancher.21
commit: 858520048dc296257f578b1967e3776320482a76
version: 109.0.6-rc.2
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/ob-team-charts.git
      subdirectory: charts/rancher-monitoring-crd/80.9.1-rancher.21
      commit: 858520048dc296257f578b1967e3776320482a76
doNotRelease: false
