url: https://github.com/rancher/ob-team-charts.git
subdirectory: charts/rancher-monitoring/80.9.1-rancher.3
commit: 47e87cfd02fddbd500585497a886f60fdebe9d4c
version: 109.0.0-rc.1
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/ob-team-charts.git
      subdirectory: charts/rancher-monitoring-crd/80.9.1-rancher.3
      commit: 47e87cfd02fddbd500585497a886f60fdebe9d4c
doNotRelease: false
