packages:
  rancher-logging:
    "4.10":
      branches:
        - branch: "dev-v2.10"
          package: rancher-logging
        - branch: "dev-v2.11"
          package: rancher-logging
        - branch: "dev-v2.12"
          package: rancher-logging
        - branch: "dev-v2.13"
          package: rancher-logging
        - branch: "dev-v2.14"
          package: rancher-logging
        - branch: "dev-v2.15"
          package: rancher-logging
  rancher-monitoring:
    "66.7":
      branches:
        - branch: "dev-v2.10"
          package: rancher-monitoring/rancher-monitoring
        - branch: "dev-v2.11"
          package: rancher-monitoring/66.7/rancher-monitoring
    "69.8":
      branches:
        - branch: "dev-v2.11"
          package: rancher-monitoring/69.8/rancher-monitoring
        - branch: "dev-v2.12"
          package: rancher-monitoring/69.8/rancher-monitoring
    "77.9":
      branches:
        - branch: "dev-v2.13"
          package: rancher-monitoring/rancher-monitoring
    "80.9":
      branches:
        - branch: "dev-v2.14"
          package: rancher-monitoring/rancher-monitoring

kuberlr-kubectl:
  dev-v2.10: release/v3.x
  dev-v2.11: release/v4.x
  dev-v2.12: release/v5.x
  dev-v2.13: release/v6.x
  dev-v2.14: release/v7.x
  dev-v2.15: main

rancher-k3s:
  "2.10": "v1.30.2+k3s1"
  "2.11": "v1.31.2+k3s1"
  "2.12": "v1.31.2+k3s1"
  "2.13": "v1.32.2+k3s1"
  "2.14": "v1.33.1+k3s1"
  "2.15": "v1.34.1+k3s1"
