rancher/mirrored-suse-observability-agent-container-tools:
  - 1.8.1-bci
rancher/mirrored-suse-observability-agent-generic-sidecar-injector:
  - d03e11f3-21
rancher/mirrored-suse-observability-agent-http-header-injector-proxy:
  - cb2eb8ab-194
rancher/mirrored-suse-observability-agent-http-header-injector-proxy-init:
  - cb2eb8ab-194
rancher/mirrored-suse-observability-agent-k8s-agent:
  - 289d9a9e
rancher/mirrored-suse-observability-agent-k8s-cluster-agent:
  - 289d9a9e
rancher/mirrored-suse-observability-agent-k8s-process-agent:
  - 5d0ec298
rancher/mirrored-suse-observability-agent-kubernetes-rbac-agent:
  - 35ec5206
rancher/mirrored-suse-observability-agent-promtail:
  - 2.9.15-2a5cc100
