rancher/harvester-cloud-provider:
  - v0.2.5
rancher/harvester-csi-driver:
  - v0.2.4
rancher/kubectl:
  - v1.33.5
rancher/prometheus-federator:
  - v4.2.1
rancher/rancher-webhook:
  - v0.8.3
rancher/system-upgrade-controller:
  - v0.16.3
