# List of images with repositories and tags (optional)
# If there is no tag, the CI will check if a chart using the image is using the latest version of the image
# If there is a tag, the CI will check if a chart using the image is using that tag
kuberlr:
  repository: rancher/kuberlr-kubectl
