rancher/fleet:
  - v0.16.0
rancher/fleet-agent:
  - v0.16.0
rancher/rancher-webhook:
  - v0.11.0
rancher/remotedialer-proxy:
  - v0.8.0
rancher/system-upgrade-controller:
  - v0.20.1
rancher/turtles:
  - v0.27.0
