rancher/fleet:
  - v0.14.10
rancher/fleet-agent:
  - v0.14.10
rancher/prometheus-federator:
  - v5.0.4
rancher/rancher-webhook:
  - v0.9.8
rancher/remotedialer-proxy:
  - v0.6.3
rancher/turtles:
  - v0.25.7
