rancher/fleet:
  - v0.15.3
rancher/fleet-agent:
  - v0.15.3
rancher/harvester-csi-driver:
  - v0.2.9
rancher/rancher-webhook:
  - v0.10.7
rancher/remotedialer-proxy:
  - v0.7.4
rancher/turtles:
  - v0.26.3
