# Branch naming conventions
branch-version: "2.14"
release-prefix: release-v
dev-prefix: dev-v

# Lifecycle retetion policy
# if 0 retain all charts versions
minor-retention-policy: 7 # minor versions to keep legacy charts versions

# allowed naming conventions at version build metadata
allowed-pre-release-naming: ["-alpha", "-beta", "-rc"]
allowed-metadata-naming: ["-rancher"]

# Version rules per release branch
# Defines the version range (min/max) for each Rancher release line
version-rules:
  "2.14":  109
  "2.13":  108
  "2.12":  107
  "2.11":  106
  "2.10":  105
  "2.9":   104
  "2.8":   103
  "2.7":   101
  "2.6":   100
