apiVersion: management.cattle.io/v3
kind: GlobalRole
displayName: Liz (Rancher AI Assistant) User
description: Grants access to the Rancher AI Assistant for users to interact with the agent through the Rancher UI.
metadata:
  name: liz-user
namespacedRules:
  cattle-ai-agent-system:
    - apiGroups:
        - ''
      resourceNames:
        - http:rancher-ai-agent:80
      resources:
        - services/proxy
      verbs:
        - get
    - apiGroups:
        - ''
      resourceNames:
        - llm-config
      resources:
        - configmaps
      verbs:
        - get
    - apiGroups:
        - apps
      resources:
        - deployments
      verbs:
        - get
        - watch
        - list
    - apiGroups:
        - ai.cattle.io
      resources:
        - aiagentconfigs
      verbs:
        - watch
        - list