apiVersion: v1
kind: Secret
metadata:
  name: llm-secret
  namespace: cattle-ai-agent-system
type: Opaque
stringData:
  OPENAI_API_KEY: "{{ .Values.openaiApiKey }}"
  OPENAI_URL: "{{ .Values.openaiUrl }}"
  OLLAMA_URL: "{{ .Values.ollamaUrl }}"
  GOOGLE_API_KEY: "{{ .Values.googleApiKey }}"
  LANGFUSE_HOST: "{{ .Values.langfuseHost }}"
  LANGFUSE_PUBLIC_KEY: "{{ .Values.langfusePublicKey }}"
  LANGFUSE_SECRET_KEY: "{{ .Values.langfuseSecretKey }}"
  AWS_REGION: "{{ .Values.awsBedrock.region }}"
  AWS_BEARER_TOKEN_BEDROCK: "{{ .Values.awsBedrock.bearerToken }}"
