{{- define "logging-operator.logging.rke2" -}}
metadata:
  name: {{ .Release.Name }}-rke2
spec:
  {{- if .Values.additionalLoggingSources.rke2.fluentd.replicas }}
  fluentd:
    scaling:
      replicas: {{ .Values.additionalLoggingSources.rke2.fluentd.replicas }}
  {{- end }}
{{- end -}}
{{- if .Values.additionalLoggingSources.rke2.enabled }}
{{- include "logging-operator.logging" (list . "logging-operator.logging.rke2") -}}
{{- end }}