#!/usr/bin/env bash
set -e

if [ -z "$(command -v yq)" ] || ! yq --version | cut -d' ' -f3 | grep -q 3.4; then
	echo "yq 3.4.x must be installed to run this script. You can use the following command to download it:"
	echo "$ curl -sLf https://github.com/mikefarah/yq/releases/download/3.4.1/yq_linux_amd64 > /usr/local/bin/yq && chmod +x /usr/local/bin/yq"
	exit 1
fi

if [ -z "$(command -v helm)" ]; then
	echo "Helm 3 must be installed to run this script. You can use the following command to download it:"
	echo "$ curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash && chmod +x /usr/local/bin/helm"
	exit 1
fi