#!/usr/bin/env bash
set -e

if [[ $(uname -s) == 'Darwin' ]]; then 
	echo "Please make sure you have helm v3 and yq v3 installed"
	exit 0
fi

# Download helm
if [[ -z $(command -v helm) ]] || [[ $(helm version --short) != "v3"* ]]; then
	curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash && chmod +x /usr/local/bin/helm
fi

# Download yq
if [[ -z $(command -v yq) ]]; then
	curl -sLf https://github.com/mikefarah/yq/releases/download/3.2.1/yq_linux_amd64 > /usr/local/bin/yq && chmod +x /usr/local/bin/yq
fi