#!/bin/bash

# Check if the file is empty
if [[ ! -s release.yaml ]]; then
  echo "release.yaml is empty!"
  exit 0
fi

yq -i release.yaml

if [[ -n $(git status --porcelain release.yaml) ]]; then
  echo "release.yaml not following yq style"
  exit 1
else
  exit 0
fi
