#!/usr/bin/env bash

for f in packages/*; do
	if [[ -f ${f}/package.yaml ]]; then
		if [[ -z $CHART || $CHART == $(basename -- ${f}) ]]; then
			if [[ $(cat ${f}/package.yaml | yq r - url) ]]; then
				rm -rf ${f}/charts
			elif [ -d ${f}/charts-crd/templates ]; then
				mv ${f}/charts-crd/templates ${f}/charts/crds
			fi
			rm -rf ${f}/charts-crd
		fi
	fi
done

for f in packages/*; do
	if [[ -z $CHART || $CHART == $(basename -- ${f}) ]]; then
		if [ -d "${f}/charts/charts" ]; then
			rm -f ${f}/charts/charts/*.tgz
		fi
	fi
done
