#!/usr/bin/env bash
set -e

delete_annotation() {
    # Functionally is the same as yq d -i $1 'annotations[$2]'
    if [[ -z ${1} ]]; then
        echo "No Chart.yaml path provided"
        exit 1
    fi
    chart_yaml="${1}"
    if [[ -z ${2} ]]; then
        echo "Did not provide field to delete in annotations listed in ${f}/charts/Chart.yaml"
        exit 1
    fi
    # escaping for awk
    field="${2/\//\\/}"
    tmpfile=$(mktemp)
    awk -f ./scripts/awk/delete_annotation.awk -v field=$field ${f}/charts/Chart.yaml > $tmpfile
    mv $tmpfile $chart_yaml
}

# Reverts changes done to a chart from the prepare-crd script to go back to using one chart
if [[ -z $1 ]]; then
    echo "No directory provided to revert charts-crd changes within"
	exit 1
fi

f=$1

if ! [[ -d ${f}/charts-crd ]]; then
    echo "Chart does not have a charts-crd/ directory to revert changes from"
    exit 1
fi

# Move CRDs back into ${f}/charts/crd/ and remove ${f}/charts-crd
mkdir -p ${f}/charts/crds/
if [[ -d ${f}/charts-crd/crd-manifest ]]; then
	mv ${f}/charts-crd/crd-manifest/* ${f}/charts/crds/
else
	mv ${f}/charts-crd/templates/* ${f}/charts/crds/
fi
rm -rf ${f}/charts-crd

if ! [[ -d ${f}/charts ]]; then
    # Main chart has already been deleted; no need to modify contents
    exit 0
fi

# Remove the validate-install-${name}-crd.yaml
name=$(cat ${f}/charts/Chart.yaml | yq r - 'name')
rm ${f}/charts/templates/validate-install-crd.yaml
# Remove additional annotations added to original chart if added
if [[ "$(yq r ${f}/charts/Chart.yaml 'annotations[catalog.cattle.io/auto-install]')" == "${name}-crd=match" ]]; then
    delete_annotation ${f}/charts/Chart.yaml "catalog.cattle.io/auto-install"
fi
