#!/usr/bin/env bash

for f in packages/*; do
	if [[ -f ${f}/package.yaml ]]; then
		if [[ -z $CHART || $CHART == $(basename -- ${f}) ]]; then
			split_crds=$(yq r ${f}/package.yaml generateCRDChart.enabled)
			if [[ "${split_crds}" == "true" && -d ${f}/charts-crd ]]; then
				./scripts/clean-crds ${f}
			fi
			if [[ $(cat ${f}/package.yaml | yq r - url) ]]; then
				rm -rf ${f}/charts
			fi
		fi
	fi
done

for f in packages/*; do
	if [[ -z $CHART || $CHART == $(basename -- ${f}) ]]; then
		if [ -d "${f}/charts/charts" ]; then
			rm -f ${f}/charts/charts/*.tgz
		fi
	fi
done
