#!/usr/bin/env bash
set -e

patchVersion() {
    if $(grep -q - <<< ${1}); then
        part1=$(echo ${1} | cut -d'-' -f1)
        part2=$(echo ${1} | cut -d'-' -f2-)
        if $(grep -q rc <<< ${part2}); then
          echo ${part1}${2}-${part2}
        else
          echo ${1}${2}
        fi
	else
        echo ${1}${2}
    fi
}

for f in packages/*; do
	if [[ -z $CHART || $CHART == $(basename -- ${f}) ]]; then
		mkdir -p assets/$(basename -- ${f})
		if [[ -d ${f}/overlay ]]; then
			cp -R ${f}/overlay/* ${f}/charts
		fi
		version=""
		if [[ -f ${f}/package.yaml ]]; then
			version=$(yq r ${f}/charts/Chart.yaml version)
			packageVersion=$(yq r ${f}/package.yaml packageVersion)
			yq w -i ${f}/charts/Chart.yaml 'version' "$(patchVersion ${version} ${packageVersion})"
		fi

		helm package ${f}/charts --destination assets/$(basename -- ${f})

		# copy over contents to charts/ folder for browsing purpose
		mkdir -p charts/$(basename -- ${f})
		cp -R ${f}/charts/* charts/$(basename -- ${f})/

		if [[ -d ${f}/charts-crd ]]; then
			packageVersion=$(yq r ${f}/package.yaml packageVersion)
			yq w -i ${f}/charts-crd/Chart.yaml 'version' "$(patchVersion ${version} ${packageVersion})"

			helm package ${f}/charts-crd --destination assets/$(basename -- ${f})

			# copy over contents to charts/ folder for browsing purpose
			mkdir -p charts/$(basename -- ${f})/charts-crd
			cp -R ${f}/charts-crd/* charts/$(basename -- ${f})/charts-crd
		fi
		helm repo index --merge ./assets/index.yaml --url assets assets
	fi
done

cp ./assets/index.yaml .
