#!/bin/bash

cd $(dirname $0)/..

if [[ "${DRONE_PULL_REQUEST}" ]]; then
  CHANGEDPATHS=$(git --no-pager diff --name-only FETCH_HEAD FETCH_HEAD~1)
else
  CHANGEDPATHS=$(git --no-pager diff --name-only HEAD~1)
fi

echo $CHANGEDPATHS