#!/bin/bash
set -e

cd $(dirname $0)/..

./scripts/prepare

# Remove special changes from optional flags before checking if Git is dirty
for f in packages/*; do
    if [[ -f ${f}/package.yaml ]]; then
        split_crds=$(cat ${f}/package.yaml | yq r - generateCRDChart.enabled)
		if [[ "${split_crds}" == "true" && -d ${f}/charts-crd ]]; then
			./scripts/clean-crds ${f}
		fi
        providesGVR="$(cat ${f}/package.yaml | yq r - providesGVR)"
		if [[ -n ${providesGVR} && -f ${f}/charts/Chart.yaml ]]; then
			if [[ "$(yq r ${f}/charts/Chart.yaml 'annotations[catalog.cattle.io/provides-gvr]')" == "${providesGVR}" ]]; then
				yq d -i ${f}/charts/Chart.yaml "annotations[catalog.cattle.io/provides-gvr]" 
			fi
		fi
    fi
done

source ./scripts/version

# Add back in special changes from optional flags
for f in packages/*; do
    if [[ -f ${f}/package.yaml ]]; then
        split_crds=$(cat ${f}/package.yaml | yq r - generateCRDChart.enabled)
		if [[ "${split_crds}" == "true" ]]; then
			./scripts/prepare-crds ${f}
		fi
        providesGVR="$(cat ${f}/package.yaml | yq r - providesGVR)"
		if [[ -n ${providesGVR} && -f ${f}/charts/Chart.yaml ]]; then
			if [[ -z "$(yq r ${f}/charts/Chart.yaml 'annotations[catalog.cattle.io/provides-gvr]')" ]]; then
				yq w -i ${f}/charts/Chart.yaml "annotations[catalog.cattle.io/provides-gvr]" "${providesGVR}"
			fi
		fi
    fi
done

if [ -n "$DIRTY" ]; then
    echo Git is dirty
    git status
    exit 1
fi

./scripts/generate-charts

./scripts/clean
