#!/bin/bash
set -e

cd $(dirname $0)/..

for f in packages/*; do
  if [[ -f ${f}/package.yaml && -d ${f}/charts ]]; then
    split_crds=$(cat ${f}/package.yaml | yq r - generateCRDChart.enabled)
    if [[ "${split_crds}" == "true" ]]; then
      git update-index --assume-unchanged ${f}/charts/crds/*
    fi
  fi
done

./scripts/prepare

source ./scripts/version

if [ -n "$DIRTY" ]; then
    echo Git is dirty
    git status
    exit 1
fi

./scripts/generate-charts

for f in packages/*; do
  if [[ -f ${f}/package.yaml && -d ${f}/charts ]]; then
    split_crds=$(cat ${f}/package.yaml | yq r - generateCRDChart.enabled)
    if [[ "${split_crds}" == "true" ]]; then
      git update-index --no-assume-unchanged ${f}/charts/crds/*
    fi
  fi
done
