#!/bin/bash
set -e

CHARTS_BUILD_SCRIPTS_REPO=https://github.com/rancher/charts-build-scripts.git
# renovate: datasource=github-releases depName=rancher/charts-build-scripts
CHARTS_BUILD_SCRIPT_VERSION="${CHARTS_BUILD_SCRIPT_VERSION:-v1.9.19}"
# renovate: datasource=github-release-attachments depName=rancher/charts-build-scripts digestVersion=v1.9.19
CHARTS_BUILD_SCRIPT_CHECKSUM_LINUX_AMD64="328985fd611dbcab2f4e27d78e2daabe1c15ba3faad66abfd384cdbae766d398"

# Branch configuration
UPSTREAM_BRANCH=release-v2.15
OLD_UPSTREAM_BRANCH=release-v2.14
