#!/bin/bash
set - e

CHARTS_BUILD_SCRIPTS_REPO=https://github.com/rancher/charts-build-scripts.git
# renovate: datasource=github-releases depName=rancher/charts-build-scripts
CHARTS_BUILD_SCRIPT_VERSION="${CHARTS_BUILD_SCRIPT_VERSION:-v1.9.33}"
# renovate: datasource=github-release-attachments depName=rancher/charts-build-scripts digestVersion=v1.9.33
CHARTS_BUILD_SCRIPT_CHECKSUM_LINUX_AMD64="fab81d57a2bee2beb6cc142c04d75177bfdd85cd6c6877b1db311178469b8e06"

