#!/bin/bash
set -e

CHARTS_BUILD_SCRIPTS_REPO=https://github.com/rancher/charts-build-scripts.git
# renovate: datasource=github-releases depName=rancher/charts-build-scripts
CHARTS_BUILD_SCRIPT_VERSION="${CHARTS_BUILD_SCRIPT_VERSION:-v1.9.26}"
# renovate: datasource=github-release-attachments depName=rancher/charts-build-scripts digestVersion=v1.9.26
CHARTS_BUILD_SCRIPT_CHECKSUM_LINUX_AMD64="ecb90d1ba0ef367923eeddc6b912c2a55370a95192e3e4796b40d12ea51b36e0"
