annotations:
  catalog.cattle.io/auto-install: rancher-compliance-crd=match
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/display-name: Rancher Compliance
  catalog.cattle.io/kube-version: '>= 1.33.0-0 < 1.36.0-0'
  catalog.cattle.io/namespace: compliance-operator-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux,windows
  catalog.cattle.io/provides-gvr: compliance.cattle.io.clusterscans/v1
  catalog.cattle.io/rancher-version: '>= 2.14.0-0 < 2.15.0-0'
  catalog.cattle.io/release-name: rancher-compliance
  catalog.cattle.io/type: cluster-tool
  catalog.cattle.io/ui-component: rancher-compliance
apiVersion: v1
appVersion: v1.4.0-rc.2
description: The compliance-operator enables running security scans on a kubernetes
  cluster
icon: file://assets/logos/rancher-compliance.svg
keywords:
- security
name: rancher-compliance
version: 109.0.0+up1.4.0-rc.2
