auto: true
url: https://github.com/rancher/ali-operator.git
chartRepoBranch: charts/v0.1
subdirectory: charts/rancher-ali-operator
workingDir: rancher-ali-operator
additionalCharts:
  - workingDir: rancher-ali-operator-crd
    upstreamOptions:
      url: https://github.com/rancher/ali-operator.git
      chartRepoBranch: charts/v0.1
      subdirectory: charts/rancher-ali-operator-crd
