url: https://github.com/rancher/compliance-operator.git
version: 107.1.0
chartRepoBranch: release/v1.0
subdirectory: chart
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/compliance-operator.git
      chartRepoBranch: main
      subdirectory: crds
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true