url: https://github.com/rancher/ob-team-charts.git
subdirectory: charts/rancher-logging/4.10.0-rancher.21
commit: 70b5dd20eeb51837b5833b2b20755639dc26e660
version: 106.0.6-rc.1
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/ob-team-charts.git
      subdirectory: charts/rancher-logging-crd/4.10.0-rancher.21
      commit: 70b5dd20eeb51837b5833b2b20755639dc26e660
doNotRelease: false
