url: https://github.com/rancher/ob-team-charts.git
subdirectory: charts/rancher-logging/4.10.0-rancher.24
commit: 3e97dd9d0c718897cfd385057eb5c3dada705876
version: 105.3.3-rc.2
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/ob-team-charts.git
      subdirectory: charts/rancher-logging-crd/4.10.0-rancher.24
      commit: 3e97dd9d0c718897cfd385057eb5c3dada705876
doNotRelease: false
