url: https://github.com/rancher/ob-team-charts.git
subdirectory: charts/rancher-logging/4.10.0-rancher.23
commit: 72b038fc15191a15c495e3c5b968b5d4312c8a43
version: 109.0.0-rc.1
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/ob-team-charts.git
      subdirectory: charts/rancher-logging-crd/4.10.0-rancher.23
      commit: 72b038fc15191a15c495e3c5b968b5d4312c8a43
doNotRelease: false
