url: https://neuvector.github.io/neuvector-helm/core-2.10.3.tgz
version: 106.0.10
additionalCharts:
- workingDir: charts-crd
  crdOptions:
    templateDirectory: crd-template
    crdDirectory: templates
