url: https://neuvector.github.io/neuvector-helm/core-2.11.1.tgz
version: 110.0.1
additionalCharts:
- workingDir: charts-crd
  crdOptions:
    templateDirectory: crd-template
    crdDirectory: templates
