url: https://neuvector.github.io/neuvector-helm/core-2.8.12.tgz
version: 106.0.7
additionalCharts:
- workingDir: charts-crd
  crdOptions:
    templateDirectory: crd-template
    crdDirectory: templates
