annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/namespace: compliance-operator-system
  catalog.cattle.io/release-name: rancher-compliance-crd
apiVersion: v1
description: Installs the CRDs for rancher-compliance.
name: rancher-compliance-crd
type: application
version: 107.9.0+up1.2.9
