global:
  cattle:
    systemDefaultRegistry: ""

systemUpgradeController:
  image:
    repository: rancher/system-upgrade-controller
    tag: v0.16.3

kubectl:
  image:
    repository: rancher/kubectl
    tag: v1.33.5
