global:
  cattle:
    systemDefaultRegistry: ""
    imagePullSecrets: []
    # imagePullSecrets:
    #   - name: secret1
    # or
    # imagePullSecrets:
    #  - secret1

systemUpgradeController:
  image:
    repository: rancher/system-upgrade-controller
    tag: v0.19.1

kubectl:
  image:
    repository: rancher/kuberlr-kubectl
    tag: v7.0.3 # For compatibility and versioning, see https://github.com/rancher/kuberlr-kubectl
