annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/display-name: Rancher Turtles
  catalog.cattle.io/kube-version: '>= 1.33.0-0 < 1.36.0-0'
  catalog.cattle.io/managed: "true"
  catalog.cattle.io/namespace: cattle-turtles-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux
  catalog.cattle.io/rancher-version: '>= 2.14.0-0 < 2.15.0-0'
  catalog.cattle.io/release-name: rancher-turtles
  catalog.cattle.io/scope: management
  catalog.cattle.io/type: cluster-tool
apiVersion: v2
appVersion: 0.26.0
description: Rancher Turtles - Cluster API integration in Rancher.
home: https://github.com/rancher/turtles/
icon: file://assets/logos/rancher-turtles.svg
keywords:
- rancher
- cluster-api
- capi
- provisioning
name: rancher-turtles
type: application
version: 109.0.0+up0.26.0
