name: Hull-Tests

on:
  pull_request:
    branches:
      - dev-v*

jobs:
  hull-tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v4

      - name: Checkout PR
        run: gh pr checkout ${{ github.event.pull_request.number }}
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Hull tests
        run: cd tests && go test -v ./...