name: Test Dependencies

on: workflow_dispatch

jobs:
  test-dependencies:
    runs-on: ubuntu-latest
    container: registry.suse.com/bci/bci-base:latest
    steps:
      - uses: actions/checkout@v4

      - name: Test Dependencies Action
        uses: ./.github/actions/dependencies

      - name: Verify Installation
        run: |
          echo "Verifying all tools..."
          docker --version
          jq --version
          git --version
          make --version
          go version
          patch --version
          gawk --version

